name: deploy  website

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  call-workflow1:
    uses: PhilBrockman/testing-cypress/.github/workflows/run-cypress-checks.yml@main
    steps:
      - uses: PhilBrockman/testing-cypress/.github/workflows/to-vercel.yml@main
          secrets:
            VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
            VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID}}
            VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID}}
