name: Run Cypress before pushing to production

on:
  push:
    branches:
      - main

jobs:
  run-cypress-checks:
    name: Run Cypress in cloud
    uses: PhilBrockman/testing-cypress/.github/workflows/run-cypress-checks.yml@main

  release:
    name: Deploy to production
    needs: [run-cypress-checks]
    name: Deploy Checked Project to Vercel
    uses: PhilBrockman/testing-cypress/.github/workflows/to-vercel.yml@main
    secrets:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID}}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID}}
