name: Run Cypress before pushing to production

on:
  push:
    branches:
      - main

jobs:
  check-then-deploy:
    steps:
      - uses: PhilBrockman/testing-cypress/.github/workflows/run-cypress-checks.yml@main
      - uses: PhilBrockman/testing-cypress/.github/workflows/to-vercel.yml@main
        secrets:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID}}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID}}
