name: Run Cypress before pushing to production

on:
  push:
    branches:
      - main

  workflow_call:

jobs:
  run-cypress-checks:
    uses: PhilBrockman/testing-cypress/.github/workflows/run-cypress-checks.yml@main

  release:
    needs: [run-cypress-checks]
    steps:
      - name: Deploy Checked Project to Vercel
        uses: PhilBrockman/testing-cypress/.github/workflows/to-vercel.yml@main
        secrets:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID}}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID}}
