name: deploy  website

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  call-workflow1:
    uses: PhilBrockman/testing-cypress/.github/workflows/run-cypress-checks.yml@main

  call-workflow2:
    uses: PhilBrockman/testing-cypress/.github/workflows/to-vercel.yml@main
